#! /bin/bash 

### BEGIN INIT INFO
# Provides:          powerAtBoot
# Required-start:    $all
# Required-stop:     $all
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6  
# Short-Description: 
# Description: 
### END INIT INFO 

case "$1" in 
	start)
		powerDir=/home/pi/eDNA
		cd $powerDir
		./ruPower
		echo "Starting powerAtBoot"
	done
	;;
	stop)
		echo "stopping powerAtBoot"
		killall powerAtBoot
	;;
	*)
		echo "Usage: /etc/init.d/powerAtBoot start|stop"
		exit 1 
	;;
esac 
done