#!/bin/bash
# run logger for power, current and volt

#directories and files needed 
utilities=/home/pi/eDNA/utilities
echo $utilities
config=/home/pi/eDNA/utilities/Config.dat
lib=/usr/local/lib/python2.7/dist-packages
#homeLib=/home/pi
#echo $config

#get PIDs  
powerPID=$(pidof python powerMeas.py)

#add directories needed to run temp,pressure,humidity app to pythonpath
export PYTHONPATH=$PYTHONPATH/$utilities:$lib

#=================================================================================
#killl apps if necessary 
#=================================================================================
#if [ $# -eq 1 ]; then
#	if [ $1 == "stop" ]; then
#		echo "STOP Requested"
#		# Kill the control GUI if it's running
#		if [ ! -z $powerPID ]; then
#			echo "Killing power app"
#			kill -9 $powerPID
#		else
#			echo "power app not running"
#		fi 
#		exit 
#	fi 
#fi 
#
#=================================================================================
#Kill running apps 
#=================================================================================
#./runPower stop 

#=================================================================================
#Run app
#=================================================================================
echo " --- RUN BOTTOM NODE ---"
python3 powerMeas.py $config &
